### ISSUE TITLE
No se especifica licencia

### ISSUE THREAD

**Issue by PuercoPop** [culqi/culqi-python#1]
IANAL pero (https://help.github.com/articles/open-source-licensing/)[el FAQ de github]:

"Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend."

Es la intención que el código sea Open Source?

**Comment by jpscaletti** [comment]
+1 Si no es de uso libre, tengo que contactarme con uds para tramitar una licencia para su uso?
Si en cambio pretenden que cualquiera pueda usarla, sIn una licencia abierta legalmente no puede hacerse.

Una licencia abierta como BSD probablemente sea lo que prefieran, por que básicamente dice "haz lo que quieras pero no me hago responsable (https://es.wikipedia.org/wiki/Licencia_BSD#Nueva_Licencia_BSD_o_BSD_modificada_.28de_3_cl.C3.A1usulas.29)

**Comment by william-culqi** [comment]
Hola, 
Sí, como comentas, la licencia BSD estaría bien. También había pensado en MIT. El lunes lo estaremos revisando y te comento.
