### ISSUE TITLE
error  print token

### ISSUE THREAD

**Issue by pikabytes** [culqi/culqi-python#4]
Buenas tengo un problema al momento de imprimir el token,   cambien las keys por la letra "x"
culqipy.public_key ="x"
culqipy.secret_key = "x"
dir_token = {'card_number': '4111111111111111',
                     'cvv': '123',
                     'currency_code': 'PEN',
                     'email': 'wmuro@me.com',
                     'expiration_month': 9,
                     'expiration_year': 2020}

token= culqipy.Token.create(dir_token)
print token

{u'merchant_message': u'Tu c\xf3digo de comercio no est\xe1 habilitado para realizar este tipo de peticiones. Cont\xe1ctate con soporte@culqi.com para obtener mas informaci\xf3n.', u'object': u'error', u'type': u'authentication_error'}

Probe los test y de igual manera error, ya que el token no devuelve nada.
alguna solucion para esto? o algo que este haciendo mal?

Gracias por su ayuda

**Comment by marti1125** [comment]
Hola @alexishayro la creación de tokens es solo para aquellos comercios que implementan su propio checkout y por defecto esa opcion esta desactivado. para activar esa opción te puedes poner en contacto con @LizRuelas .

por otro lado puede crear tokens utilizando nuestro [js](https://github.com/culqi/culqi-python-example-BETA/blob/master/flask/templates/index.html#L21)

**Comment by LizRuelas** [comment]
Hola @alexishayro  me parece que ya te envié un correo desde integrate@culqi.com si no es así
por favor proporcionarme tu correo.

Quedo atenta, saludos :)

**Comment by marti1125** [comment]
@alexishayro  alguna novedad ?

**Comment by richardcancino17** [comment]
@LizRuelas Hola, me está pasando el mismo error, mi correo es : richard.cancinov@gmail.com, espero que me pueda ayudar ya que necesito hacer testeos.

Saludos
